// <auto-generated />
using System;
using EmpolyeeTrailMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpolyeeTrailMonitor.Migrations
{
    [DbContext(typeof(EmpolyeeTrailContext))]
    [Migration("20200225024750_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmpolyeeTrailMonitor.Models.EmpolyeeTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BmapLap")
                        .HasColumnType("real");

                    b.Property<float>("BmapLng")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("DistanceSecond")
                        .HasColumnType("int");

                    b.Property<float>("GPSX")
                        .HasColumnType("real");

                    b.Property<float>("GPSY")
                        .HasColumnType("real");

                    b.Property<bool>("IsCar")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EmpolyeeTrail");
                });
#pragma warning restore 612, 618
        }
    }
}
